#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cmath>
#include <cstring>
struct V5Control{int64_t clock;uint32_t n,slots,delay,rfc;float dt;};
struct V5Context{id<MTLDevice>device;id<MTLCommandQueue>queue;id<MTLLibrary>library;id<MTLComputePipelineState>update,prepare,propagate,finalize,applyPending;id<MTLBuffer>ptr,post,weight,v,g,r,last,drive,previous,events,eventCounts,spikeCounts,flags,epoch,av,ag,control,propArgs,pending;NSUInteger n,e,width;};
static void enc(id<MTLCommandBuffer>cb,id<MTLComputePipelineState>p,NSArray<id<MTLBuffer>>*b,NSUInteger threads,NSUInteger width){id<MTLComputeCommandEncoder>x=[cb computeCommandEncoder];[x setComputePipelineState:p];for(NSUInteger i=0;i<b.count;i++)[x setBuffer:b[i] offset:0 atIndex:i];[x dispatchThreads:MTLSizeMake(threads,1,1) threadsPerThreadgroup:MTLSizeMake(width,1,1)];[x endEncoding];}
extern "C"{
void*metal_create_v5(int n,long long e,const long long*ptr,const int*post,const float*weight,const char*path,int width){@autoreleasepool{auto*c=new V5Context{};c->n=n;c->e=e;c->device=MTLCreateSystemDefaultDevice();if(!c->device){delete c;return nullptr;}c->queue=[c->device newCommandQueue];c->width=MIN(NSUInteger(width>0?width:256),c->device.maxThreadsPerThreadgroup.width);NSError*er=nil;c->library=[c->device newLibraryWithURL:[NSURL fileURLWithPath:[NSString stringWithUTF8String:path]] error:&er];if(!c->library){delete c;return nullptr;}auto p=[&](NSString*s){return[c->device newComputePipelineStateWithFunction:[c->library newFunctionWithName:s] error:&er];};c->update=p(@"v5_update");c->prepare=p(@"v5_prepare");c->propagate=p(@"v5_propagate");c->finalize=p(@"v5_finalize");c->applyPending=p(@"v5_apply_pending_resets");if(!c->update||!c->prepare||!c->propagate||!c->finalize||!c->applyPending){delete c;return nullptr;}auto cp=[&](const void*x,NSUInteger z){return[c->device newBufferWithBytes:x length:z options:MTLResourceStorageModeShared];};auto z=[&](NSUInteger x){return[c->device newBufferWithLength:x options:MTLResourceStorageModeShared];};c->ptr=cp(ptr,(n+1)*8);c->post=cp(post,e*4);c->weight=cp(weight,e*4);c->v=z(n*4);c->g=z(n*4);c->r=z(n*2);c->last=z(n*8);c->drive=z(n*4);c->previous=z(n*4);c->events=z(19ull*n*4);c->eventCounts=z(19*4);c->spikeCounts=z(n*4);c->flags=z(n*4);c->epoch=z(n*4);c->pending=z(n);c->av=z(4096);c->ag=z(4096);c->propArgs=z(12);float*A=(float*)c->av.contents,*B=(float*)c->ag.contents;for(int i=0;i<1024;i++){A[i]=std::exp(-.1f*i/20.f);B[i]=std::exp(-.1f*i/5.f);}V5Control ctl{0,uint32_t(n),19,18,22,.1f};c->control=cp(&ctl,sizeof(ctl));return c;}}
void metal_destroy_v5(void*p){if(p)delete static_cast<V5Context*>(p);}
int metal_load_v5(void*p,const float*v,const float*g,const int16_t*r,const float*d,const float*previous,const int32_t*events,const int32_t*eventCounts,const int32_t*spikeCounts,const uint8_t*flags,const int64_t*last,const int64_t*clock){if(!p)return 0;auto*c=(V5Context*)p;NSUInteger n=c->n;memcpy(c->v.contents,v,n*4);memcpy(c->g.contents,g,n*4);memcpy(c->r.contents,r,n*2);memcpy(c->drive.contents,d,n*4);memcpy(c->previous.contents,previous,n*4);memcpy(c->events.contents,events,19*n*4);memcpy(c->eventCounts.contents,eventCounts,76);memcpy(c->spikeCounts.contents,spikeCounts,n*4);uint32_t*ff=(uint32_t*)c->flags.contents;for(NSUInteger i=0;i<n;i++)ff[i]=flags[i]?1:0;memset(c->epoch.contents,0,n*4);memset(c->pending.contents,0,n);memcpy(c->last.contents,last,n*8);((V5Control*)c->control.contents)->clock=*clock;return 1;}
int metal_set_drive_v5(void*p,const float*d){if(!p)return 0;auto*c=(V5Context*)p;memcpy(c->drive.contents,d,c->n*4);return 1;}int metal_zero_counts_v5(void*p){if(!p)return 0;auto*c=(V5Context*)p;memset(c->spikeCounts.contents,0,c->n*4);return 1;}
int metal_read_v5(void*p,const int32_t*idx,uint32_t count,int32_t*counts,float*volts){if(!p)return 0;auto*c=(V5Context*)p;auto*sc=(int32_t*)c->spikeCounts.contents;auto*v=(float*)c->v.contents;for(uint32_t i=0;i<count;i++){counts[i]=sc[idx[i]];volts[i]=v[idx[i]];}return 1;}
long long metal_total_spikes_v5(void*p){if(!p)return -1;auto*c=(V5Context*)p;auto*sc=(int32_t*)c->spikeCounts.contents;long long total=0;for(NSUInteger i=0;i<c->n;i++)total+=sc[i];return total;}
int metal_step_v5(void*p,int steps){@autoreleasepool{if(!p||steps<1)return 0;auto*c=(V5Context*)p;int64_t start=((V5Control*)c->control.contents)->clock;id<MTLCommandBuffer>cb=[c->queue commandBuffer];for(int tick=0;tick<steps;tick++){int64_t clock=start+tick;id<MTLComputeCommandEncoder>x=[cb computeCommandEncoder];[x setComputePipelineState:c->update];NSArray*b=@[c->v,c->g,c->r,c->drive,c->previous,c->events,c->eventCounts,c->spikeCounts,c->flags,c->last,c->av,c->ag,c->control,c->pending];for(NSUInteger i=0;i<b.count;i++)[x setBuffer:b[i] offset:0 atIndex:i];[x setBytes:&clock length:sizeof(clock) atIndex:14];[x setBuffer:c->propArgs offset:0 atIndex:15];[x dispatchThreads:MTLSizeMake(c->n,1,1) threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];x=[cb computeCommandEncoder];[x setComputePipelineState:c->propagate];b=@[c->ptr,c->post,c->weight,c->events,c->g,c->flags,c->control];for(NSUInteger i=0;i<b.count;i++)[x setBuffer:b[i] offset:0 atIndex:i];[x setBytes:&clock length:sizeof(clock) atIndex:7];[x dispatchThreadgroupsWithIndirectBuffer:c->propArgs indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];}int64_t boundary=start+steps-1;id<MTLComputeCommandEncoder>x=[cb computeCommandEncoder];[x setComputePipelineState:c->applyPending];NSArray*b=@[c->v,c->g,c->r,c->pending,c->control,c->last,c->drive,c->av,c->ag];for(NSUInteger i=0;i<b.count;i++)[x setBuffer:b[i] offset:0 atIndex:i];[x setBytes:&boundary length:sizeof(boundary) atIndex:9];[x dispatchThreads:MTLSizeMake(c->n,1,1) threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status!=MTLCommandBufferStatusCompleted)return 0;((V5Control*)c->control.contents)->clock=start+steps;return 1;}}
}
