#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cmath>
#include <cstring>
struct Ctl{int64_t clock;uint32_t n,slots,delay,rfc;float dt;};
struct X{id<MTLDevice>d;id<MTLCommandQueue>q;id<MTLLibrary>l;id<MTLComputePipelineState>settle,prep,update,mark,prepTargets,materialize,scatter,finish;id<MTLBuffer>ptr,post,w,v,g,r,last,drive,previous,events,eventCounts,spikeCounts,flags,active[2],activeCounts,pending,epoch,targets,targetCount,av,ag,ctl,activeArgs,sourceArgs,targetArgs;NSUInteger n,e,width;};
static id<MTLComputeCommandEncoder> begin(id<MTLCommandBuffer>cb,id<MTLComputePipelineState>p,NSArray<id<MTLBuffer>>*b){id<MTLComputeCommandEncoder>x=[cb computeCommandEncoder];[x setComputePipelineState:p];for(NSUInteger i=0;i<b.count;i++)[x setBuffer:b[i] offset:0 atIndex:i];return x;}
static void direct(id<MTLCommandBuffer>cb,id<MTLComputePipelineState>p,NSArray<id<MTLBuffer>>*b,NSUInteger n,NSUInteger w){id<MTLComputeCommandEncoder>x=begin(cb,p,b);[x dispatchThreads:MTLSizeMake(n,1,1) threadsPerThreadgroup:MTLSizeMake(w,1,1)];[x endEncoding];}
extern "C"{
void*metal_create_v6(int n,long long e,const long long*ptr,const int*post,const float*w,const char*path,int width){@autoreleasepool{auto*c=new X{};c->n=n;c->e=e;c->d=MTLCreateSystemDefaultDevice();if(!c->d){delete c;return nullptr;}c->q=[c->d newCommandQueue];c->width=MIN(NSUInteger(width>0?width:256),c->d.maxThreadsPerThreadgroup.width);NSError*er=nil;c->l=[c->d newLibraryWithURL:[NSURL fileURLWithPath:[NSString stringWithUTF8String:path]] error:&er];if(!c->l){delete c;return nullptr;}auto p=[&](NSString*s){return[c->d newComputePipelineStateWithFunction:[c->l newFunctionWithName:s] error:&er];};c->settle=p(@"v6_settle_drive");c->prep=p(@"v6_prepare");c->update=p(@"v6_update_active");c->mark=p(@"v6_mark_targets");c->prepTargets=p(@"v6_prepare_targets");c->materialize=p(@"v6_materialize_targets");c->scatter=p(@"v6_scatter");c->finish=p(@"v6_finish");if(!c->settle||!c->prep||!c->update||!c->mark||!c->prepTargets||!c->materialize||!c->scatter||!c->finish){delete c;return nullptr;}auto cp=[&](const void*x,NSUInteger z){return[c->d newBufferWithBytes:x length:z options:MTLResourceStorageModeShared];};auto z=[&](NSUInteger n){return[c->d newBufferWithLength:n options:MTLResourceStorageModeShared];};c->ptr=cp(ptr,(n+1)*8);c->post=cp(post,e*4);c->w=cp(w,e*4);c->v=z(n*4);c->g=z(n*4);c->r=z(n*2);c->last=z(n*8);c->drive=z(n*4);c->previous=z(n*4);c->events=z(19ull*n*4);c->eventCounts=z(76);c->spikeCounts=z(n*4);c->flags=z(n*4);c->active[0]=z(n*4);c->active[1]=z(n*4);c->activeCounts=z(8);c->pending=z(n);c->epoch=z(n*4);c->targets=z(n*4);c->targetCount=z(4);c->av=z(4096);c->ag=z(4096);c->activeArgs=z(12);c->sourceArgs=z(12);c->targetArgs=z(12);float*A=(float*)c->av.contents,*B=(float*)c->ag.contents;for(int i=0;i<1024;i++){A[i]=std::exp(-.1f*i/20.f);B[i]=std::exp(-.1f*i/5.f);}Ctl ctl{0,uint32_t(n),19,18,22,.1f};c->ctl=cp(&ctl,sizeof(ctl));return c;}}
void metal_destroy_v6(void*p){if(p)delete(X*)p;}
int metal_load_v6(void*p,const float*v,const float*g,const int16_t*r,const float*d,const float*previous,const int32_t*events,const int32_t*eventCounts,const int32_t*spikeCounts,const int32_t*active,const uint8_t*flags,const int32_t*nactive,const int64_t*last,const int64_t*clock){if(!p)return 0;auto*c=(X*)p;NSUInteger n=c->n;memcpy(c->v.contents,v,n*4);memcpy(c->g.contents,g,n*4);memcpy(c->r.contents,r,n*2);memcpy(c->drive.contents,d,n*4);memcpy(c->previous.contents,previous,n*4);memcpy(c->events.contents,events,19*n*4);memcpy(c->eventCounts.contents,eventCounts,76);memcpy(c->spikeCounts.contents,spikeCounts,n*4);uint32_t*f=(uint32_t*)c->flags.contents;for(NSUInteger i=0;i<n;i++)f[i]=flags[i]?1:0;memset(c->activeCounts.contents,0,8);uint32_t parity=uint32_t(*clock)&1u;memcpy(c->active[parity].contents,active,n*4);((int32_t*)c->activeCounts.contents)[parity]=*nactive;memset(c->pending.contents,0,n);memset(c->epoch.contents,0,n*4);memcpy(c->last.contents,last,n*8);((Ctl*)c->ctl.contents)->clock=*clock;return 1;}
int metal_set_drive_v6(void*p,const float*d){if(!p)return 0;auto*c=(X*)p;memcpy(c->drive.contents,d,c->n*4);return 1;}int metal_zero_counts_v6(void*p){if(!p)return 0;memset(((X*)p)->spikeCounts.contents,0,((X*)p)->n*4);return 1;}int metal_read_v6(void*p,const int32_t*i,uint32_t n,int32_t*counts,float*volts){if(!p)return 0;auto*c=(X*)p;auto*C=(int32_t*)c->spikeCounts.contents;auto*V=(float*)c->v.contents;for(uint32_t q=0;q<n;q++){counts[q]=C[i[q]];volts[q]=V[i[q]];}return 1;}
int metal_step_v6(void*p,int steps){@autoreleasepool{
 if(!p||steps<1)return 0;auto*c=(X*)p;int64_t start=((Ctl*)c->ctl.contents)->clock;id<MTLCommandBuffer>cb=[c->q commandBuffer];
 uint32_t startParity=uint32_t(start)&1u;id<MTLComputeCommandEncoder>settleEncoder=begin(cb,c->settle,@[c->v,c->g,c->r,c->drive,c->previous,c->flags,c->active[startParity],c->activeCounts,c->last,c->av,c->ag,c->ctl]);[settleEncoder setBuffer:c->activeCounts offset:startParity*4 atIndex:7];[settleEncoder setBytes:&start length:8 atIndex:12];[settleEncoder dispatchThreads:MTLSizeMake(c->n,1,1) threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[settleEncoder endEncoding];
 for(int tick=0;tick<steps;tick++){
  int64_t clock=start+tick;uint32_t cur=uint32_t(clock)&1u,next=cur^1u;
  id<MTLComputeCommandEncoder>x=begin(cb,c->prep,@[c->activeCounts,c->eventCounts,c->targetCount,c->activeArgs,c->sourceArgs,c->ctl]);
  [x setBytes:&clock length:8 atIndex:6];[x setBuffer:c->active[cur] offset:0 atIndex:7];[x dispatchThreads:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(1,1,1)];[x endEncoding];
  x=begin(cb,c->update,@[c->active[cur],c->active[next],c->activeCounts,c->v,c->g,c->r,c->drive,c->events,c->eventCounts,c->spikeCounts,c->flags,c->pending,c->last,c->av,c->ag,c->ctl]);
  [x setBuffer:c->activeCounts offset:next*4 atIndex:2];[x setBytes:&clock length:8 atIndex:16];[x dispatchThreadgroupsWithIndirectBuffer:c->activeArgs indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(256,1,1)];[x endEncoding];
  x=begin(cb,c->mark,@[c->ptr,c->post,c->events,c->epoch,c->targets,c->targetCount,c->flags,c->active[next],c->activeCounts,c->ctl]);[x setBuffer:c->activeCounts offset:next*4 atIndex:8];[x setBytes:&clock length:8 atIndex:10];[x dispatchThreadgroupsWithIndirectBuffer:c->sourceArgs indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];
  direct(cb,c->prepTargets,@[c->targetCount,c->targetArgs],1,1);
  x=begin(cb,c->materialize,@[c->targets,c->targetCount,c->v,c->g,c->r,c->drive,c->last,c->av,c->ag,c->ctl]);[x setBytes:&clock length:8 atIndex:10];[x dispatchThreadgroupsWithIndirectBuffer:c->targetArgs indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(256,1,1)];[x endEncoding];
  x=begin(cb,c->scatter,@[c->ptr,c->post,c->w,c->events,c->g,c->ctl]);[x setBytes:&clock length:8 atIndex:6];[x dispatchThreadgroupsWithIndirectBuffer:c->sourceArgs indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];
 }
 int64_t boundary=start+steps-1;id<MTLComputeCommandEncoder>x=begin(cb,c->finish,@[c->v,c->g,c->r,c->pending,c->last,c->drive,c->av,c->ag,c->ctl]);[x setBytes:&boundary length:8 atIndex:9];[x dispatchThreads:MTLSizeMake(c->n,1,1) threadsPerThreadgroup:MTLSizeMake(c->width,1,1)];[x endEncoding];
 [cb commit];[cb waitUntilCompleted];if(cb.status!=MTLCommandBufferStatusCompleted)return 0;((Ctl*)c->ctl.contents)->clock=start+steps;return 1;
}}
}
