// Sparse throughput backend: GPU-resident active lists, delayed event ring,
// unique-target materialization, then relaxed atomic accumulation.
#include <metal_stdlib>
using namespace metal;
struct V6Control { long clock; uint n,slots,delay,rfc; float dt; };
struct DispatchArgs { uint x,y,z; };
inline void evolve(int i,long now,float current,device float*v,device float*g,device short*r,device long*last,device const float*av,device const float*ag,float dt){long d=now-last[i];if(d<=0)return;int frozen=r[i]>0?r[i]-1:0;int skip=int(min(d,long(frozen)));r[i]=d>=r[i]?0:short(r[i]-d);d-=skip;if(d>0){float a=d<1024?av[d]:exp(-dt*float(d)/20.f),b=d<1024?ag[d]:exp(-dt*float(d)/5.f);v[i]=-52.f+(v[i]+52.f)*a+current*(1.f-a)+g[i]*(a-b)/3.f;g[i]*=b;}last[i]=now;}

kernel void v6_settle_drive(device float*v[[buffer(0)]],device float*g[[buffer(1)]],device short*r[[buffer(2)]],device const float*drive[[buffer(3)]],device float*previous[[buffer(4)]],device atomic_uint*flags[[buffer(5)]],device int*active[[buffer(6)]],device atomic_int*active_count[[buffer(7)]],device long*last[[buffer(8)]],device const float*av[[buffer(9)]],device const float*ag[[buffer(10)]],device const V6Control*c[[buffer(11)]],constant long&clock[[buffer(12)]],uint i[[thread_position_in_grid]]){if(i>=c->n)return;if(drive[i]!=previous[i]){evolve(int(i),clock-1,previous[i],v,g,r,last,av,ag,c->dt);previous[i]=drive[i];uint expected=0;if(atomic_compare_exchange_weak_explicit(flags+i,&expected,1,memory_order_relaxed,memory_order_relaxed)){int q=atomic_fetch_add_explicit(active_count,1,memory_order_relaxed);active[q]=int(i);}}}

kernel void v6_prepare(device atomic_int*active_counts[[buffer(0)]],device atomic_int*event_counts[[buffer(1)]],device atomic_int*target_count[[buffer(2)]],device DispatchArgs*active_args[[buffer(3)]],device DispatchArgs*source_args[[buffer(4)]],device const V6Control*c[[buffer(5)]],constant long&clock[[buffer(6)]],device int*active_in[[buffer(7)]],uint tid[[thread_position_in_grid]]){if(tid)return;uint cur=uint(clock)&1u,next=cur^1u,slot=uint(clock%long(c->slots));uint na=uint(max(0,atomic_load_explicit(active_counts+cur,memory_order_relaxed))),ns=uint(max(0,atomic_load_explicit(event_counts+slot,memory_order_relaxed)));atomic_store_explicit(active_counts+next,0,memory_order_relaxed);atomic_store_explicit(target_count,0,memory_order_relaxed);atomic_store_explicit(event_counts+slot,0,memory_order_relaxed);uint padded=((na+255)/256)*256;for(uint q=na;q<padded;q++)active_in[q]=-1;active_args[0]={padded/256,1,1};source_args[0]={ns,1,1};}

kernel void v6_update_active(device const int*active_in[[buffer(0)]],device int*active_out[[buffer(1)]],device atomic_int*active_out_count[[buffer(2)]],device float*v[[buffer(3)]],device float*g[[buffer(4)]],device short*r[[buffer(5)]],device const float*drive[[buffer(6)]],device int*events[[buffer(7)]],device atomic_int*event_counts[[buffer(8)]],device int*spike_counts[[buffer(9)]],device atomic_uint*flags[[buffer(10)]],device uchar*pending[[buffer(11)]],device long*last[[buffer(12)]],device const float*av[[buffer(13)]],device const float*ag[[buffer(14)]],device const V6Control*c[[buffer(15)]],constant long&clock[[buffer(16)]],uint q[[thread_position_in_grid]]){int i=active_in[q];if(i<0)return;if(pending[i]){v[i]=-52.f;g[i]=0.f;r[i]=short(c->rfc);pending[i]=0;}evolve(i,clock,drive[i],v,g,r,last,av,ag,c->dt);if(r[i]==0&&v[i]>-45.f){uint future=uint((clock+long(c->delay))%long(c->slots));int p=atomic_fetch_add_explicit(event_counts+future,1,memory_order_relaxed);events[future*c->n+uint(p)]=i;spike_counts[i]++;pending[i]=1;}bool keep=v[i]>-45.f||drive[i]>7.f||drive[i]+g[i]>7.f;if(keep){int p=atomic_fetch_add_explicit(active_out_count,1,memory_order_relaxed);active_out[p]=i;}else atomic_store_explicit(flags+i,0,memory_order_relaxed);}

kernel void v6_mark_targets(device const long*ptr[[buffer(0)]],device const int*post[[buffer(1)]],device const int*events[[buffer(2)]],device atomic_uint*epoch[[buffer(3)]],device int*targets[[buffer(4)]],device atomic_int*target_count[[buffer(5)]],device atomic_uint*flags[[buffer(6)]],device int*active_out[[buffer(7)]],device atomic_int*active_out_count[[buffer(8)]],device const V6Control*c[[buffer(9)]],constant long&clock[[buffer(10)]],uint lane[[thread_index_in_threadgroup]],uint rank[[threadgroup_position_in_grid]],uint width[[threads_per_threadgroup]]){uint slot=uint(clock%long(c->slots)),token=(uint(clock)&0x7fffffffu)+1u;int source=events[slot*c->n+rank];for(long e=ptr[source]+long(lane);e<ptr[source+1];e+=long(width)){int target=post[e];uint old=atomic_exchange_explicit(epoch+target,token,memory_order_relaxed);if(old!=token){int q=atomic_fetch_add_explicit(target_count,1,memory_order_relaxed);targets[q]=target;}uint expected=0;if(atomic_compare_exchange_weak_explicit(flags+target,&expected,1,memory_order_relaxed,memory_order_relaxed)){int q=atomic_fetch_add_explicit(active_out_count,1,memory_order_relaxed);active_out[q]=target;}}}

kernel void v6_prepare_targets(device const atomic_int*count[[buffer(0)]],device DispatchArgs*args[[buffer(1)]],uint tid[[thread_position_in_grid]]){if(!tid){uint n=uint(max(0,atomic_load_explicit(count,memory_order_relaxed)));args[0]={(n+255)/256,1,1};}}
kernel void v6_materialize_targets(device const int*targets[[buffer(0)]],device const atomic_int*count[[buffer(1)]],device float*v[[buffer(2)]],device float*g[[buffer(3)]],device short*r[[buffer(4)]],device const float*drive[[buffer(5)]],device long*last[[buffer(6)]],device const float*av[[buffer(7)]],device const float*ag[[buffer(8)]],device const V6Control*c[[buffer(9)]],constant long&clock[[buffer(10)]],uint q[[thread_position_in_grid]]){uint n=uint(max(0,atomic_load_explicit(count,memory_order_relaxed)));if(q<n){int i=targets[q];evolve(i,clock,drive[i],v,g,r,last,av,ag,c->dt);}}
kernel void v6_scatter(device const long*ptr[[buffer(0)]],device const int*post[[buffer(1)]],device const float*weight[[buffer(2)]],device const int*events[[buffer(3)]],device atomic_float*g[[buffer(4)]],device const V6Control*c[[buffer(5)]],constant long&clock[[buffer(6)]],uint lane[[thread_index_in_threadgroup]],uint rank[[threadgroup_position_in_grid]],uint width[[threads_per_threadgroup]]){uint slot=uint(clock%long(c->slots));int source=events[slot*c->n+rank];for(long e=ptr[source]+long(lane);e<ptr[source+1];e+=long(width))atomic_fetch_add_explicit(g+post[e],weight[e],memory_order_relaxed);}
kernel void v6_finish(device float*v[[buffer(0)]],device float*g[[buffer(1)]],device short*r[[buffer(2)]],device uchar*pending[[buffer(3)]],device long*last[[buffer(4)]],device const float*drive[[buffer(5)]],device const float*av[[buffer(6)]],device const float*ag[[buffer(7)]],device const V6Control*c[[buffer(8)]],constant long&boundary[[buffer(9)]],uint i[[thread_position_in_grid]]){if(i>=c->n)return;if(pending[i]){v[i]=-52.f;g[i]=0.f;r[i]=short(c->rfc);pending[i]=0;}evolve(int(i),boundary,drive[i],v,g,r,last,av,ag,c->dt);}
